### ISSUE TITLE
page reload issue on dslreports.com

### ISSUE THREAD

**Issue by jawz101** [KevinRoebert/ClearUrls#11]
http://www.dslreports.com/shownews/FCC-Commissioner-Wants-Your-Broadband-Availability-Horror-Story-140621

**Comment by KevinRoebert** [comment]
We are examining the issue.

**Comment by KevinRoebert** [comment]
We analyzed the problem extensively. It seems that the website is trying to load excessively the advertising scripts.
We're have add some new rules, so that the page loads faster and the facebook like button is now also available.
If you're waiting a few seconds the site stops loading the ad scripts.

Attached a screenshot of the new addon log. There you can see **that only tracking scripts and pages** are blocked.
![unbenannt](https://user-images.githubusercontent.com/28713602/32974186-81aee1e6-cbfc-11e7-86eb-0e8d709acf7c.PNG)

**Comment by jawz101** [comment]
Cool.  Fun stuff
