### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by Decopi** [KevinRoebert/ClearUrls#16]
Hi, please just two simple questions:

1) What are the main differences between ClearURLs and PureURL in terms of system performance, quantitative and qualitative URL garbage removing, etc?

2) Is there any reason we don't see URLs adds-on unifying functions such as "clearing", "redirecting", "skipping" etc all-in-one?

Thank you!

**Comment by KevinRoebert** [comment]
**_To question 1:_**

> 1. What are the main differences between ClearURLs and PureURL in terms of system performance, quantitative and qualitative URL garbage removing, etc?

The main differences between ClearURLs and Pure URL is that Pure URL only has 13 rules to remove garbage fields.
> By default, Pure URL removes these garbage fields:
— utm_source, utm_medium, utm_term, utm_content, utm_campaign (spyware fields for the analytics.google.com)
— yclid (spyware fields for the metrika.yandex.ru)
— fb_action_ids, fb_action_types, fb_ref, fb_source, action_object_map, action_type_map, action_ref_map (spyware fields from the facebook.com)

ClearURLs has 65 rules to remove garbage fields and much of them are **regex-rules**, so the rule does not only block one field, it blocks all fields with the same structure (see here https://en.wikipedia.org/wiki/Regular_expression). ClearURLs use since day one also the new WebExtensions, so the addon works on all new browsers.
I can't say much about the performance of Pure URL because I don't know the source code. Here's the next difference, ClearURLs is open source, so everyone can join in to the project and/or can check the source code to error or malicious code.

We also responsive for our user wishes, e.g. we add so much features after user reviews:
- https://github.com/KevinRoebert/ClearUrls/commit/942e0950a498e96395bbfd16c1b4109ba30cb34c
- https://github.com/KevinRoebert/ClearUrls/commit/1c1dbc3538ddf4eba75195b3d6cce10fe787676d
- https://github.com/KevinRoebert/ClearUrls/commit/203f33cb9935575545869eeb9952412fee8a3ba7
- https://github.com/KevinRoebert/ClearUrls/commit/c256461340d4f04496e639e1245a8a872fbfbc42
- https://github.com/KevinRoebert/ClearUrls/commit/c32e0ecec7f6959f92d46c89939faec0d2945d02
- https://github.com/KevinRoebert/ClearUrls/commit/b6886bba80215a3ff089ab10d9a9241e5d79344a
- https://github.com/KevinRoebert/ClearUrls/commit/5b1172b7b6063c5622b79c6581402ccbf251047d
- https://github.com/KevinRoebert/ClearUrls/commit/aabcaf16c5cb3d8c46710fc69bc837ad232eabde
- https://github.com/KevinRoebert/ClearUrls/commit/092182c83ae669324e36e185b20fbfb387d68e85
- https://github.com/KevinRoebert/ClearUrls/commit/b306347ab5e8fedb26427e4d984a022a86ffff14
- https://github.com/KevinRoebert/ClearUrls/commit/a3c013b4bf634a7da8edb9e9bd0f90ad352304f2
- https://github.com/KevinRoebert/ClearUrls/commit/735d22d6f6f7e674cf1143600cef2ed63a641441
- https://github.com/KevinRoebert/ClearUrls/commit/6edf9de9cb483164fb6d586173c74fddbc96a0bc
- https://github.com/KevinRoebert/ClearUrls/commit/b78982bafa93dbc3c693ad9c14fbd293c501d25c
- https://github.com/KevinRoebert/ClearUrls/commit/6fc89a8b1ad67b78f7b7d86d079fe0adbfc4fecf
- https://github.com/KevinRoebert/ClearUrls/commit/3ba9ef05e79d37f694e521727e20eea0902d0c0c
- https://github.com/KevinRoebert/ClearUrls/commit/6f64682067b374430afca8adf63d31f4cb57ccd5
- https://github.com/KevinRoebert/ClearUrls/commit/f6f3c8eda8ad0ff3e985a824ea8dfc1ddec9415f

**_To question 2:_**

> 2. Is there any reason we don't see URLs adds-on unifying functions such as "clearing", "redirecting", "skipping" etc all-in-one?

Yes and No. It is possible but so much work. Only the functions which has this addon is a hard piece of work to maintain. We're add the feature "redirecting" a time ago and the help requests since then increase significantly.

**Comment by Decopi** [comment]
@KevinRoebert , thank you for your answer.

Two things:

1) You can see my feedback in your ClearURLs page reviews. You deserved my 5 stars.

2) I suggested ClearURLs as a must add-on, at [https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions](url)

Congratulations and again thanks for your effort!

PS: Feel free to close this issue.

**Comment by KevinRoebert** [comment]
Thanks for your feedback, I am glad to hear that you like the addon 👍

**Comment by Decopi** [comment]
@KevinRoebert feel free to answer @Thorin-Oakenpants comments:

https://github.com/ghacksuserjs/ghacks-user.js/issues/294#issuecomment-350358192
