### ISSUE TITLE
ClearURLs 1.1.2.5: use of the word 'counter'

### ISSUE THREAD

**Issue by grahamperrin** [KevinRoebert/ClearUrls#21]
## Toolbar counter

This switch has a good name. 

## Reset counter

A better name for this button will be: 

- Reset statistics

**Comment by Thorin-Oakenpants** [comment]
Just some ideas to throw at you. Don't get me wrong, there is nothing wrong with the current display/wording - it's all functional, looks pretty neat, and is totally usable - but it could possibly be better in terms of layout (spacings, paddings, placement, indents, bold/normal text etc)

Here is a mock up (excuse my useless photoshop skills), some items I did not include in the mock up
![clearurls-ideas](https://user-images.githubusercontent.com/16656956/33922405-828c3a40-e02f-11e7-826d-9c334c415ffc.png)

- not in the mockup, but make **Configs**, **Statistic Totals** and **Rule-&-Hash-Status** all **BOLD**
- indent (in the mock up I did both left and right sides as well as the stats bar) entries under these three ^^^ section headings
- unbold filters, logging, toolbar counter - not shown in mockup - as these are section items, not section headers
- move counter reset into stats section (I abbreviated it to just Reset)
- stats section - rename to something like "Statistics (Totals)" or "Statistic Totals" and shorten all three stat entry titles, which allows removal of separate lines for the figures
- move version number into header (you don't even need the word `version`)
- lighten the ClearURLs shade of blue, it's a bit too dark IMO (especially noticeable when webpage backgrounds are dark as well)
- notice header has more even padding top and bottom to center content
- possibly remove link to log on "ClearURLs" title and instead add a monochrome logger icon to the right (and recenter everything) - so its [orange trash can icon] title&version [white logger icon]. This removes any ambiguity or no knowledge of how to access the logger
- about the only thing left that annoys my sense of equilibrium, is that "toolbar counter" takes two lines, but I do not think it can be shortened, as it would confuse people

Just some ideas for you, also the reduced height will maybe help on mobile (no idea, height seems ok since it is static). Like em, hate em .. all up to you :)

**Comment by KevinRoebert** [comment]
Thanks for the input. With the next version of ClearURLs comes a new interface.

**Comment by KevinRoebert** [comment]
I hope you all like the new version 1.2 (https://github.com/KevinRoebert/ClearUrls/commit/0f68d65e9a29c1f2ea87644c8f80703b96b4beaa) 👍

**Comment by Thorin-Oakenpants** [comment]
this excites me the most

> - Remove siteBlockedAlert.html page. We're show now nothing.

**Comment by Thorin-Oakenpants** [comment]
lol .. one more suggestion

move "log" button at bottom to the same as the "reset" one -> move it into the Config section so it's in the same section as the log switch - I'd go for the same size etc as "reset" but use white text on gray background

**Comment by grahamperrin** [comment]
@Thorin-Oakenpants I suggest opening a new issue for 1.2.

**Comment by grenzor** [comment]
Shouldn't the 'up-to-date' under Rules-Status be centered? Currently it's aligned right.

**Comment by KevinRoebert** [comment]
Yes :)

LG
Kevin Röbert
