### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by Rtizer-9** [KevinRoebert/ClearUrls#25]
1. Is there any specific reason you included doubleclick.net domain?, cause there are some websites which detect such kind of blocking and flags you as adblock user. Being a user of such awesome addon mostly means he/she is already using an adblock addon which is already blocking doubleclick.net domain.

![gthb](https://user-images.githubusercontent.com/35103368/34570480-edfad39a-f191-11e7-9109-885872971de3.png)

visit [https://raw.githubusercontent.com/anarki999/Adblock-List-Archive/master/Better.fyiTrackersBlocklist.txt](url) and search "anti" on the page.

As you can see, in the above better.fyi filterlist an exception to some google ad domains are added to **make adblock undetectable**, I think these can be managed more efficiently through an adblock extension which supports whitelisting such as ublock origin or ghostery etc. 

2. Does this extension support **t.co** redirection and intermediate tracking by twitter cause its reach and tracking methods are far more invasive than bit.ly or similar domains. If not, are there any chances of including it?

3. Is there any chance the functionality of **Link Cleaner** addon [https://addons.mozilla.org/en-US/firefox/addon/link-cleaner/](url) can be included: it **removes facebook's l.facebook.com redirection** and that too **without injecting javascript** in webpage as it hangs the whole page and increase memory and cpu usage like **affiliate killer userscript**? is there any chance you can include **affiliate and immediate redirection** functionality just like this addon?

4. Does this addon completely remove any information sent to target domain with removed parameters or are there any chances of connecting to domains with those parameter and referrer filled domains if you hover over such kind of links and also does it just changes the url **AFTER** you have connected to the parameters filled domain or it let us connect only after removing the parameters?

Being said that, a **huge respect and love for your out of the box approach towards this thing which sets this addon apart from the rest**. 

These questions are asked out of curiosity and to request to add support for features so as to minimize the installation of such kind of addons which are doing almost similar function so as to decrease the page hangs, memory and cpu consumption, incompatibility between each other and separately configuring each and every addon.

**Comment by Atavic** [comment]
1. So you are using adblock and those scripts are whitelisted to avoid being labeled as an adblock user? 
Also, to be precise, those scripts aren't hosted on google domains: 
hk01 belongs to  Amazon.com, Inc.

4. Completely remove any information sent to target domain isn't an easy task. If you hover over some links the page can do something unexpected. I prevent most of these actions with these entries in about:config for Mozilla based browsers:

network.captive-portal-service.enabled", false // (FF52+)
dom.popup_allowed_events", "click dblclick

For more info, look at the user.js [here](https://github.com/ghacksuserjs/ghacks-user.js/)

>and also does it just change the url AFTER you have connected to the parameters-filled domain?

When you load an html page, the browser without addons renders the page on screen as it is. Addons/Webextensions modify the code before it is available on screen.

**Comment by Atavic** [comment]
1. So you are using adblock and those scripts are whitelisted to avoid being labeled as an adblock user?
Also, to be precise, those scripts aren't hosted on google domains:
`hk01` belongs to Amazon.com, Inc.

4. Completely remove any information sent to target domain isn't an easy task. If you hover over some links the page can do something unexpected. I prevent most of these actions with these entries in about:config for Mozilla based browsers:

`network.captive-portal-service.enabled false` // (FF52+)
`dom.popup_allowed_events "click dblclick"`

For more info, look at the user.js [here](https://github.com/ghacksuserjs/ghacks-user.js)

>and also does it just change the url AFTER you have connected to the parameters-filled domain?

When you load an html page, the browser without addons renders the page on screen as it is. Addons/Webextensions modify the code before it is available on screen.

**Comment by Atavic** [comment]
1. So you are using adblock and those scripts are whitelisted to avoid being labeled as an adblock user?
Also, to be precise, those scripts aren't hosted on google domains:
hk01 belongs to Amazon.com, Inc.

4. Completely remove any information sent to target domain isn't an easy task. If you hover over some links the page can do something unexpected. I prevent most of these actions with these entries in about:config for Mozilla based browsers:

`network.captive-portal-service.enabled false // (FF52+)`
`dom.popup_allowed_events "click dblclick"`

For more info, look at the user.js [here](https://github.com/ghacksuserjs/ghacks-user.js)

>and also does it just change the url AFTER you have connected to the parameters-filled domain?

When you load an html page, the browser without addons renders the page on screen as it is. Addons/Webextensions modify the code before it is available on screen.

**Comment by Rtizer-9** [comment]
I wasn't talking about hk01 domains but

@@||*.*/*/ads.js$script 
@@||*.*/*/adsbygoogle.js$script

which are covered as you can see below
![screenshot_20180105_004126](https://user-images.githubusercontent.com/35103368/34580173-0290a224-f1b2-11e7-94dd-f129234c2937.png)

**Comment by Rtizer-9** [comment]
@KevinRoebert waiting eagerly for your reply

**Comment by KevinRoebert** [comment]
@Rtizer-9 sorry for the delay, I've fix #26.

> Is there any specific reason you included doubleclick.net domain?, cause there are some websites which detect such kind of blocking and flags you as adblock user. Being a user of such awesome addon mostly means he/she is already using an adblock addon which is already blocking doubleclick.net domain.

Yes, because doubleclick.net do nothing else as tracking the user. With this simple rule we can block much of tracking scripts, canvas, pictures, etc.

But you're right, it might be better to let handle this by an adblock addon. We will think about it and maybe, we add an option to disable this feature.

> Does this extension support t.co redirection and intermediate tracking by twitter cause its reach and tracking methods are far more invasive than bit.ly or similar domains. If not, are there any chances of including it?

**Redirection:** Not at this moment, but it's a great idea. I think we will include this in the next time.
**Tracking:** 
```
"rules": [
                "(ref_)?src=[^\\/|\\?|&]*(\\/|&(amp;)?)?"
            ]
```
It's not so easy to get all the tracking elements from a service. We are happy about every commit that gives us a new tracking field. Feel free to send us lots of tracking fields, also from twitter.

> Is there any chance the functionality of Link Cleaner addon https://addons.mozilla.org/en-US/firefox/addon/link-cleaner/ can be included: it removes facebook's l.facebook.com redirection and that too without injecting javascript in webpage as it hangs the whole page and increase memory and cpu usage like affiliate killer userscript? is there any chance you can include affiliate and immediate redirection functionality just like this addon?

Definitely there is a chance, but I do this in my free time and this addon is much work. I can promise, that more redirections and rules will follow, but it needs time.

> Does this addon completely remove any information sent to target domain with removed parameters or are there any chances of connecting to domains with those parameter and referrer filled domains if you hover over such kind of links and also does it just changes the url AFTER you have connected to the parameters filled domain or it let us connect only after removing the parameters?

This question is hard to answer, because, as @Atavic already wrote, there are much ways to track users.
It's possible with scripts, images, canvas, webrtc and much more. This addon focus on blocking tracking fields in urls, in other words we delete from a url specific GET elements.

The GET elements, or as we call them, fields are very effective tracking tricks to track people through links. 
For example you send a friend an amazon link, so now amazon knows what are the interests from you and your friend and can combine the informations. So it's easy to build a relationship network.

We use the webExtensions function `webRequest.onBeforeRequest`. The following picture from mozillas MDN shows the request flow:

![webRequest flow](https://mdn.mozillademos.org/files/13376/webRequest-flow.png)

ClearURLs start at the top of the webRequest flow, so we can check the request before something was done. But only all webRequests does the addon check, if other types of connection exist in firefox, the addon does not check this.

> [...] or it let us connect only after removing the parameters

Yes!

I hope I could help you.

**Comment by Rtizer-9** [comment]
Great :blush:. Hoping for awesome releases.

**Comment by grenzor** [comment]
In my opinion, blocking domains like doubleclick should be best left to adblock addons and ClearURLs should deal purely with redirection/cleaning of tracking links.
