### ISSUE TITLE
ClearUrls is nice, but is killing my browser

### ISSUE THREAD

**Issue by ArchangeGabriel** [KevinRoebert/ClearUrls#26]
A lot of webpages are taking a long time to load (e.g. DuckDuckGo), while some stuck the browser for ever, like this one (/!\ Save your session first, you will have to SIGTERM Firefox if affected):
https://itsfoss.com/best-icon-themes-ubuntu-16-04/

I’ve reproduced this in a clean Nightly profile (just installing ClearUrls and going to above URL), but haven’t had the time to check with release/beta.

**Comment by KevinRoebert** [comment]
Hi, I am currently investigating the problem. In fact, it only occurs in the dev and beta versions. Under stable, it is not reproducible.

In the debugger I found a few codes that I can optimize significantly. I hope that ClearURLs will in the next version fast at the dev and the beta.

Thanks for reporting.

The following codes consumes 71,06% of the time:
`clearurls.js:230
clearurls.js:325
clearurls.js:426`

**Comment by KevinRoebert** [comment]
Ok, I found the mistake. It's not directly on ClearUrls, but on the websites. The long processing time through ClearUrls comes, because some pages, especially DuckDuckGo, get their fonts as `data: application/font-woff;charset=utf-8;base64` via the request interface of the browser.

As a result, ClearUrls thinks it's a URL. Base64 coded fonts are, of course, summed, for the matching over regex very expensive.

I will now try to write an exception for anything that is not a valid url, then the addon should be **much** faster.

I also made some more performance improvements. For example: the addon now accepts all requests and returns a promis, if ClearUrls does not have an answer within 1000ms, the request is skipped.

Here is a shortened example from a duckduckgo request over the webRequest handler from firefox:
`data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAGYMAA4AAAAAowAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABRAAAABwAAAAcckwii0dERUYAAAFgAAAAHwAAACABMwAET1MvMgAAAYAAAABAAAAAYJYFacxjbWFwAAABwAAAAUEAAAKi6kAXkmdhc3AAAAMEAAAACAAAAAj//wADZ2x5ZgAAAwwAAFnuAACMgOFsk4doZWFkAABc/AAAAC4AAAA2DP0UgmhoZWEAAF0sAAAAGgAAACQPogeuaG10eAAAXUgAAAEHAAACFodAcgtsb2NhAABeUAAAAg4AAAIO/oLadm1heHAAAGBgAAAAHwAAACABWQC1bmFtZQAAYIAAAAGbAAADVi8qdoNwb3N0AABiHAAAA+cAAApGwPo//ndlYmYAAGYEAAAABgAAAAayr1bhAAAAAQAAAADMPaLPAAAAANMHHI4AAAAA0wdjLXjaY2BkYGDgA2IJBhBgYmBkYGRkBZIsYB4DAASNADkAeNpjYGY/xTiBgZWBhVWEZQMDA8M0CM20h8GIKQLIB0phB6He4X4MDqp/vrqzXwDxgaQGkGJEUqLAwAgANrQKyHja3ZC9SwNBEMXnkqgcuzcGxOIgxYGkuO78JMHmNMQkoCKmkIhI/GhiFRshXRoLO1vBv0U7tdFGFAzWaqXO7o426nkkYGFv44N5w4Ph92AAIAm9yYAVO1jHcbK6OWW1470GIfRBJvtBNg2RSyPkU0BTlKcCFalMNdqgBrVoX1nKVq7yVV6Falbb2tW+zuuKqZgVUzN10zAtc2COOMU2u+zzKOe4wKUoAojpQGkaJo+yMX2MchTG9BJVqU5btEttBSqp0spTQZdu6bT2dKBDUzZLXfqmaZq2OWTgfk6zxwGPc8jFKOoMDKbwCz/xH[…]`

**Comment by KevinRoebert** [comment]
This short code fix the issue. I will upload the new version as fast as possible.

```
function isDataURL(requestDetails) {
    var s = requestDetails.url;

    return s.substring(0,4) == "data";
}
```

**Comment by KevinRoebert** [comment]
Can anybody confirm the fix on version 1.2.1.0?

**Comment by ArchangeGabriel** [comment]
It seems fixed indeed. ;)

**Comment by Thorin-Oakenpants** [comment]
> Here is an example from a duckduckgo request over the webRequest handler from firefox:

*Much more intricate and detailed than past books without being overly complicated. Perhaps the international angle helped. The addition of more characters and more levels of intrigue and the masterful building of suspense make this regular read into a must read! 5 stars* - Thorin

**Comment by Thorin-Oakenpants** [comment]
@KevinRoebert - from another (unrelated) issue (at our ghacks user.js repo which I @ 'ed you in on) I ended up doing some tests and have found that ClearURLs causes a significant delay in web content loading - it will vary by site of course. Its been bugging me for weeks. I can give you a particular site for testing/debugging, which I would rather email to you

In a nilla 57.0.4 profile this site will load/render in about a quarter of a second, add ClearURLs and it now takes 2 to 3 seconds. Let me know how to give you the site URL, and if you want to just deal with it in here or open a new issue. ClearURLs is not blocking anything on the site/URL in the test

In my testing I noticed something else. Nothing else in loaded in the browser - just the one URL. Nothing in cache etc. Every load is preceded by a clear everything. Since nothing is blocked, the only item being counted in the stats are elements. First page load the element counter said `60`, clear cache + reset counter, reload and the element counter said `119` .. repeat, and counter says `178`, repeat .. `237` .. on this one page the element counter is increasing by 59 elements cumulatively - even if you open the URl in a new tab. Closing FF (i.e session end) and resetting the stats, and it starts from `60` again. So something is clearly going on here.

**Comment by KevinRoebert** [comment]
@Thorin-Oakenpants It would be great if you could send me the URL via email. The support email for ClearURLs is _clearurls@kevinroebert.de_.

In the email, you can attach all the information you have. Of course, if you want, you can also open a new issue.

> First page load the element counter said 60, clear cache + reset counter, reload and the element counter said 119 .. repeat, and counter says 178, repeat .. 237 .. on this one page the element counter is increasing by 59 elements cumulatively - even if you open the URl in a new tab. Closing FF (i.e session end) and resetting the stats, and it starts from 60 again. So something is clearly going on here.

At repairing #26, I noticed something similar, but I did not have the time to take a closer look. Please also send me your information, preferably an example, so that I can take a closer look.

**Comment by Thorin-Oakenpants** [comment]
I'm wondering if the element counting gets worse and worse (bigger and bigger) the longer the session goes on until it slows things down? Not sure what happens with element counting when the url changes (same url different tab showed the cumulative affect)

Will send the URL via email, but not sure what I can add in the details. And I have no scientific time measuring. But after several weeks of my daily local news site being really noticeably slow on EVERY page (3 seconds+) to now being almost instant again, there's something going on. My PoC (for lack of a better word) was to compare a few page loads of said site in a nilla profile (clearing cache between loads), then doing the same with ClearURLs - difference seems to be day and night

email on the way

**Comment by Thorin-Oakenpants** [comment]
OK, so as I was typing it all out for you, I re-ran the tests (without uBo) and tried something - I reset the counter (my stats are in the email) and lo and behold, it's all good again

so it's definitely something to do with that element counting I think - over time it causes issues. I was at 370K elements, 16K blocked, over 29 days since install. It wasn't blocking anything on the site, just element counting, and that one site I use a lot over each session. I'll leave it to you for now. PS see my note about the element count adding 1 on a reset when it can't.

**Comment by Thorin-Oakenpants** [comment]
I spoke too soon - it ~~is~~ was slightly better with the stats reset, but now its getting progressively worse and fast. As soon as I disable ClearURLs, its back to speedy load times. Something going on with that site and the counters

**Comment by Thorin-Oakenpants** [comment]
Hotfix seems to work a treat :kiss:
