### ISSUE TITLE
strange filter result of rule [a-zA-Z]*ref=[^\/|\?|&]*(\/|&(amp;)?)?

### ISSUE THREAD

**Issue by crssi** [KevinRoebert/ClearUrls#29]
Before processing
`http://www.facebook.com/plugins/like.php?locale=sl_SI&href=http://24ur.com/bin/jokes.php?joke_id=1491&layout=standard&show_faces=true&width=250&action=like&colorscheme=light&height=28&show_faces=false`

After processing:
`http://www.facebook.com/plugins/like.php?locale=sl_SI&/24ur.com/bin/jokes.php?joke_id=1491&layout=standard&show_faces=true&width=250&action=like&colorscheme=light&height=28&show_faces=false`

Rule:
`[a-zA-Z]*ref=[^\/|\?|&]*(\/|&(amp;)?)?`

**Comment by KevinRoebert** [comment]
This happens because our rule checks until the next `/` or `?` or `&`. Unfortunately, that's in a Ref URL immediately. We will come up with something for these special cases.

**Comment by crssi** [comment]
I know from the regex rule. Just reported it for improvement. ;)

**Comment by KevinRoebert** [comment]
Hi, we've checked this issue. It's not a problem of ClearURLs, it is a problem of facebook and/or the page owner.

> `http://www.facebook.com/plugins/like.php?locale=sl_SI&href=http://24ur.com/bin/jokes.php?joke_id=1491&layout=standard&show_faces=true&width=250&action=like&colorscheme=light&height=28&show_faces=false`

Is not a valid URL, because the `href=` url has to be formated like this:
`http://www.facebook.com/plugins/like.php?locale=sl_SI&href=http%3A%2F%2F24ur.com%2Fbin%2Fjokes.php%3Fjoke_id%3D1491%26layout%3Dstandard%26show_faces%3Dtrue%26width%3D250%26action%3Dlike%26colorscheme%3Dlight%26height%3D28%26show_faces%3Dfalse`

The problem is out of our reach.

**Comment by crssi** [comment]
Understood.

But we know how this goes:
Page owner will never comply to overcome those problems and also almost no user of CleanURL will go into the "fight" with page owners.
User of CleanURL will always have breakage in this or such cases.
User will cease to use CleanURL.

**Comment by KevinRoebert** [comment]
I understand what you want to say. It is frustrating for users that some poorly written pages do not work properly. 

However, we can only use the functions provided by the WebExtensions API. There I can get the request url only as a string. If this would be wrong formatted by the website, then it is impossible for me to find out the correct formatting, since either the following fields belong to the request url, or to the destination url. 

If anyone knows how to make a distinction with WebExtensions, then please just write in here.

**Comment by Atavic** [comment]
The link
`https://www.facebook.com/plugins/like.php?locale=en_GB&href=http://24ur.com/bin/jokes.php?joke_id=1491&layout=standard&show_faces=true&width=250&action=like&colorscheme=light`
is the FB "like button". It is meant to track the user. 

>it is a problem of facebook and/or the page owner.

Like other issues with this webextension and other ones, social sites require the customer to be fully tracked and start giving problems when they spot some kind of tampering/blocking of big data harvest.

Now, I have similar problems on other social sites and I use a second browser for that.
If I had to use only one browser, I'd either whitelist the site or disactivate the webextension giving me problems.

Last note: it's not the webext that has problems here, but it's the site code that tries hard to break the webext.
