### ISSUE TITLE
Add Custom URL

### ISSUE THREAD

**Issue by Machou** [KevinRoebert/ClearUrls#30]
Hello

Possible to add custom URL ?

Or add :

https://www.facebook.com/?ref=logo
https://www.facebook.com/groups/000000000000/?ref=bookmarks
https://www.facebook.com/?sk=h_chr

Thanks

**Comment by KevinRoebert** [comment]
Hey @Machou,

for now it is not possible to add own rules, but we will implement this function in the addon. Please have a look on our [project page](https://github.com/KevinRoebert/ClearUrls/projects/3). There we have add the planing for the function since 20 days. Once we have enough free time, we will implement this feature. Please have some patience until then.

We will review your proposed rules and then implement them as soon as possible.

**Comment by Atavic** [comment]
These referrers are internal to facebook only.

**Comment by KevinRoebert** [comment]
> These referrers are internal to facebook only.

@Atavic Do you have a source for this?

If it really is just an internal Facebook ref, then it does not make any sense to delete them. Facebook knows in this case, even without the fields, which was previously visited.

It looks different if these refs have any effect when sending URLs.

**Comment by Atavic** [comment]
I just looked at the source. 

`ref=logo` and `ref=bookmarks` are surely related to FB only
`sk=h_chr` is a bit of a mistery, but appears on FB main page only.

**Comment by KevinRoebert** [comment]
Hm, okay. I will close this issue first. If anyone finds out that this refs are _not just Facebook internally_, then we'll build rules for it.
