### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Kusresa** [KevinRoebert/ClearUrls#31]
I just installed this on Android but even when installed all counters are stuck at 0 so I'm assuming it doesn't work. Can Android support be added?

**Comment by Atavic** [comment]
Which browser are you using?

**Comment by KevinRoebert** [comment]
Hi, right now I can not comment on that because I do not have Android. I'm thinking of buying one for testing. But maybe a VM is enough. Until then I can not say if it's a problem of your browser or smartphone or if the addon does not work on Android.

Maybe someone else could also test whether it works on his Android or not?

**Comment by KevinRoebert** [comment]
A special thanks to Hektor for the informations about an android VM. I've tested it, but it's not so easy, because Firefox can't be debugged on an android device, I've to create a USB Connection between the device and a computer with the Firefox dev edition. Because it's to much work to emulate an USB connection, I've buyed an android device. So I can test ClearURLs under android and it will be in the futer available under android.

**Comment by Atavic** [comment]
:+1: Great!

**Comment by KevinRoebert** [comment]
ClearURLs works in version 1.2.1.3 under android. In the futer we've to add some more rules for mobile fields for better protection, but it works.

For now, in the debugg mode are some errors, because under android the style functions are not existing.
The reason for the android problem was only a simple `window` listener. I will fix the remaining, invisible error messages on Android in the coming days.

However, anyone who wants to download the version 1.2.1.3 now on the Firefox add-on page and use ClearURLs as usual, since the remaining error messages have only hint level and not impede the functional flow.
