### ISSUE TITLE
?ref=producthunt

### ISSUE THREAD

**Issue by grahamperrin** [KevinRoebert/ClearUrls#34]
For example, 

`https://mapsofmind.com/?ref=producthunt` referred from <https://www.producthunt.com/posts/mapsofmind>

**Comment by KevinRoebert** [comment]
Thank you for the notification. I will think of something to implement this.

**Comment by KevinRoebert** [comment]
Can anybody confirm the update?

**Comment by Thorin-Oakenpants** [comment]
https://github.com/KevinRoebert/ClearUrls/commit/3d7e3a4977376adc4feb4c9d4f0160cee58cce06 - is this update/fix related to this issue?

When I look at our repo's traffic (you'll have to use yours under `Insights>Traffic` to see what I mean), and wish to drill down into one of the top 10 domains (eg reddit), then, what happens is the page loads, the ClearURLs badge briefly flickers with `1`, and then the page returns to the Traffic url and the ClearURL badge is clear again (because the page changed), and the whole thing happens in the blink of an eye

I am also unable to get anything in the logger.

example
- `https://github.com/user/repo/graphs/traffic` or `https://github.com/user/repo/graphs/traffic#top-domains` (they are the same page)

where I try to view a link such as 
`https://github.com/user/repo/graphs/traffic?referrer=reddit.com#top-domains`

The only way to stop this is to disable ClearURLs, but as I said, I couldn't catch anything in the logger for some reason. 

I'm just guessing that `?referrer=*` is being blocked here via that patch?

**Comment by KevinRoebert** [comment]
The last patch actually causes this behavior.
The rule `[a-zA-Z_]*ref[a-zA-Z_]*=[^\/|\?|&]*(\/|&(amp;)?)?` Blocks the request.

I will write an exception for github. Most of the time the **ref** fields are just for tracking, so we block them globally and then have to write exceptions for non-tracking pages, e.g. github.
