### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by sciguyryan** [KevinRoebert/ClearUrls#4]
Hi there!

This report is for Firefox nightly. This one seems to be similar to the one I reported about Google Mail attachments.

I noticed this morning that CleanURLs breaks the use of Google Docs, it throws up an error and documents cannot be created or edited. I checked to ensure that CleanURLs was the underlying issue by disabling it and attempting to create or edit a document.

After disabling the extension the Google Docs functions without an issue.

I'm not sure if there is anything you can do about this but I figured that I would let you know regardless!

**Comment by KevinRoebert** [comment]
We have added an exception for the google docs and drive XHR requests on `docs.google` and `google./upload/drive`

Now it should work. Please write a comment, if it has worked or not. We must for this type of bug always add a new exception, because the add-on should block as much as possible.

Thanks for reporting.

**Comment by sciguyryan** [comment]
Yep, that seems to have fixed it. Thanks!
