### ISSUE TITLE
Consider migrating to another project platform

### ISSUE THREAD

**Issue by elypter** [KevinRoebert/ClearUrls#52]
If you haven't heard already Microsoft has just bought Github. This feels very much like a tactical quisition to combat free software. They are also known to let projects they bought from competitors rot or to actively make them bad. If you want to migrate to gitlab then it is quite easy. https://www.youtube.com/watch?v=VYOXuOg9tQI however i would not trust Microsoft to keep the required API accessible forever if they see users migrating.

**Comment by KevinRoebert** [comment]
I also regretfully read this message today. I do not trust Microsoft in open source. That's why I am exporting the entire repo to gitlab. In the future I will push all updates into the gitlab repo. But I will leave this repo still open, if some do not want to switch to gitlab.

However, ClearURLs is only actively maintained on gitlab. But I will still try to push the current changes on GitHub.

**Comment by ArchangeGabriel** [comment]
Please give use the link when done. E)

**Comment by KevinRoebert** [comment]
Here is the link to the new repo: https://gitlab.com/KevinRoebert/ClearUrls
GitLab needed 18 hours for the import, therefore only now the url.

**Comment by KevinRoebert** [comment]
Since we moved to GitLab, all new ClearURLs versions are pointing to the new repository. If you still have old settings that show the rule and hash files on GitHub, I recommend that you change them to GitLab so you can continue with the latest version of the rule.

Please change your settings as shown in the screenshot (the red area).
![change_to_gitlab](https://user-images.githubusercontent.com/28713602/41054757-8f0be06c-69bf-11e8-9830-0adbbcc808a2.PNG)

**Comment by elypter** [comment]
could you post the links for copy&paste

**Comment by KevinRoebert** [comment]
Yes :D
