### ISSUE TITLE
request users are somehow notified of rule changes

### ISSUE THREAD

**Issue by jawz101** [KevinRoebert/ClearUrls#9]
Since updates to data.json are done server-side, for safety it would be nice to know when/how the rules were changed.  While I trust you I think I should know when the rules change.  Not only from a security perspective but also to aid in testing rule changes.

**Comment by KevinRoebert** [comment]
We love security. That's why we think this proposal is great. We will implement a function that uses hash values to check if the _data.json_ has changed. If so, the changelog of github is pointed out.

Until we finish this feature, please do the following:
Please check github from time to time to see if anything has changed in the _data.json_.

**Comment by KevinRoebert** [comment]
We're have add your request to the new version 1.1.2.5. Please have some patience until firefox has finish the review.
